### ISSUE TITLE
Create World representation

### ISSUE THREAD

**Issue by battila7** [infectnet/infectnet-server#7]
As of the `Investigate World` issue, create the representation of the game World.

**Comment by szabom5** [comment]
The size of the Map should be adjusted by the admin, when a server starts running. But this feature relies on the front-end, thus a constant 1000*1000 limit will be used.

**Comment by szabom5** [comment]
The Cellular Automaton needs some specific limit numbers, e.g. how many steps it should take. These numbers can be adjusted, and this way the `cave` and `rock` ratio changes. With the right numbers set, a rather good map can be constructed.

The only problem is that there is no guarantee, that no small islands separate from the "big" coherent cave system are not created in the process. 
This is a problem because when we generate the initial starting positions of the Players, and the resources, or any other Entity's first position, we only take into consideration that the Tile should be of type `cave`. And it would be inadvisable to be completely separated from everything else on the map.

As a first attempt to solve this, we could use a flood-fill algorithm, to check if the cave system is big enough compared to the size of the whole map. Also to select the found tiles of the cave system and change all other tiles to `rock`. This way only the coherent `cave` tiles will be on the map, any other tile will be of the type `rock`.

Also for the comfort of the players, the map will be bordered(with one tile around the map), so no one will think there are more caves to go through, where  the map ends.
